// ============================================================
// Mock data — Kerala locations
// ============================================================
import type { Ticket, Ward } from '@/types';

export const MOCK_WARDS: Ward[] = [
  { id: 'w1', ward_number: 1,  ward_name: 'Thiruvananthapuram Central', zone: 'South Zone',   authority_email: 'ward1@kerala.gov', authority_name: 'Rajan Nair',      created_at: '2024-01-01T00:00:00Z' },
  { id: 'w2', ward_number: 2,  ward_name: 'Kochi Ernakulam',            zone: 'Central Zone', authority_email: 'ward2@kerala.gov', authority_name: 'Priya Menon',     created_at: '2024-01-01T00:00:00Z' },
  { id: 'w3', ward_number: 3,  ward_name: 'Kozhikode City',             zone: 'North Zone',   authority_email: 'ward3@kerala.gov', authority_name: 'Suresh Kumar',    created_at: '2024-01-01T00:00:00Z' },
  { id: 'w4', ward_number: 4,  ward_name: 'Thrissur',                   zone: 'Central Zone', authority_email: 'ward4@kerala.gov', authority_name: 'Anitha Thomas',   created_at: '2024-01-01T00:00:00Z' },
  { id: 'w5', ward_number: 5,  ward_name: 'Kollam',                     zone: 'South Zone',   authority_email: 'ward5@kerala.gov', authority_name: 'Deepak Pillai',   created_at: '2024-01-01T00:00:00Z' },
];

export const MOCK_TICKETS: Ticket[] = [
  {
    id: 't1', ticket_number: 'DW-2026-00001',
    title: 'Storm drain blocked near Secretariat',
    description: 'Large debris accumulation causing water to overflow onto the road after monsoon. Situation is worsening.',
    latitude: 8.5074, longitude: 76.9574,
    address: 'Near Kerala Secretariat, Thiruvananthapuram',
    ward_id: 'w1', ward_number: 1, ward: MOCK_WARDS[0],
    status: 'open', priority: 'critical',
    ai_severity_tag: 'Critical Waterlogging', ai_confidence: 0.93,
    photo_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    resolved_photo_url: null,
    reporter_name: 'Ananya Krishnan', reporter_phone: '9876543210', reporter_email: 'ananya@example.com',
    assigned_officer_id: null, assigned_officer_name: null, resolution_notes: null,
    sla_hours: 48, escalated_at: null, escalated_to: null, resolved_at: null,
    created_at: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 50 * 3600 * 1000).toISOString(),
  },
  {
    id: 't2', ticket_number: 'DW-2026-00002',
    title: 'Canal clogged with plastic waste near Marine Drive',
    description: 'Plastic bags and household garbage blocking canal flow near the backwaters. Foul smell reported.',
    latitude: 9.9312, longitude: 76.2673,
    address: 'Marine Drive, Kochi, Kerala',
    ward_id: 'w2', ward_number: 2, ward: MOCK_WARDS[1],
    status: 'in_progress', priority: 'high',
    ai_severity_tag: 'Severe Blockage', ai_confidence: 0.87,
    photo_url: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=600',
    resolved_photo_url: null,
    reporter_name: 'Rohit Varma', reporter_phone: '9123456780', reporter_email: null,
    assigned_officer_id: 'u1', assigned_officer_name: 'Priya Menon', resolution_notes: null,
    sla_hours: 48, escalated_at: null, escalated_to: null, resolved_at: null,
    created_at: new Date(Date.now() - 20 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
  {
    id: 't3', ticket_number: 'DW-2026-00003',
    title: 'Minor debris in roadside drain — SM Street',
    description: 'Leaves and small branches accumulating near the spice market. Water flow reduced but not fully blocked.',
    latitude: 11.2588, longitude: 75.7804,
    address: 'SM Street, Kozhikode, Kerala',
    ward_id: 'w3', ward_number: 3, ward: MOCK_WARDS[2],
    status: 'resolved', priority: 'low',
    ai_severity_tag: 'Minor Debris', ai_confidence: 0.78,
    photo_url: 'https://images.unsplash.com/photo-1566417713940-fe7c737a9ef2?w=600',
    resolved_photo_url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600',
    reporter_name: 'Kavitha Nair', reporter_phone: null, reporter_email: 'kavitha@example.com',
    assigned_officer_id: 'u2', assigned_officer_name: 'Suresh Kumar',
    resolution_notes: 'Drain cleared. Debris removed and disposed at municipal yard.',
    sla_hours: 48, escalated_at: null, escalated_to: null,
    resolved_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    created_at: new Date(Date.now() - 30 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 't4', ticket_number: 'DW-2026-00004',
    title: 'Manhole overflowing on Swaraj Round',
    description: 'Sewage overflow creating health hazard. Strong odour throughout the area. Children nearby at risk.',
    latitude: 10.5276, longitude: 76.2144,
    address: 'Swaraj Round, Thrissur, Kerala',
    ward_id: 'w4', ward_number: 4, ward: MOCK_WARDS[3],
    status: 'escalated', priority: 'critical',
    ai_severity_tag: 'Critical Waterlogging', ai_confidence: 0.95,
    photo_url: 'https://images.unsplash.com/photo-1546424729-cd09a8a16c4c?w=600',
    resolved_photo_url: null,
    reporter_name: 'Deepak Mohan', reporter_phone: '8800123456', reporter_email: null,
    assigned_officer_id: null, assigned_officer_name: null, resolution_notes: null,
    sla_hours: 48,
    escalated_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    escalated_to: 'Kerala Municipal Commissioner Office',
    resolved_at: null,
    created_at: new Date(Date.now() - 56 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
  },
  {
    id: 't5', ticket_number: 'DW-2026-00005',
    title: 'Gutter blocked after monsoon flooding',
    description: 'Street gutter completely blocked, water standing 6 inches deep near Kollam beach road bus stop.',
    latitude: 8.8932, longitude: 76.6141,
    address: 'Beach Road, Kollam, Kerala',
    ward_id: 'w5', ward_number: 5, ward: MOCK_WARDS[4],
    status: 'open', priority: 'high',
    ai_severity_tag: 'Moderate Flooding Risk', ai_confidence: 0.83,
    photo_url: 'https://images.unsplash.com/photo-1606761568499-6d2451b23c66?w=600',
    resolved_photo_url: null,
    reporter_name: null, reporter_phone: null, reporter_email: null,
    assigned_officer_id: null, assigned_officer_name: null, resolution_notes: null,
    sla_hours: 48, escalated_at: null, escalated_to: null, resolved_at: null,
    created_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
  },
  {
    id: 't6', ticket_number: 'DW-2026-00006',
    title: 'Flood canal blocked near Alappuzha Backwaters',
    description: 'Tourism-facing canal blocked with hyacinth and plastic. Boat traffic affected.',
    latitude: 9.4981, longitude: 76.3388,
    address: 'Canal Road, Alappuzha (Alleppey), Kerala',
    ward_id: 'w2', ward_number: 2, ward: MOCK_WARDS[1],
    status: 'open', priority: 'high',
    ai_severity_tag: 'Severe Blockage', ai_confidence: 0.89,
    photo_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600',
    resolved_photo_url: null,
    reporter_name: 'Thomas Mathew', reporter_phone: '9745123456', reporter_email: null,
    assigned_officer_id: null, assigned_officer_name: null, resolution_notes: null,
    sla_hours: 48, escalated_at: null, escalated_to: null, resolved_at: null,
    created_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];
